config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('show.urls')),
    path('show/', include('django.contrib.auth.urls'))
]
urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

show/urls.py
from django.urls import path
from . import views

app_name = "show"

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post_create', views.PostCreateView.as_view(), name='post_create'),
    path('parts_create', views.PartsCreateView.as_view(), name='parts_create'),
    path('<int:pk>/post_delete', views.PostDelete.as_view(), name='delete'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('user_create', views.UserCreateView.as_view(), name='user_create')
]

show/models.py
from django.db import models
from django.core import validators
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

SEASONS_CHOICES = (
    ('春', '春'),
    ('夏', '夏'),
    ('秋', '秋'),
    ('冬', '冬'),
)

PART_CHOICES = (
    ('アウター', 'アウター'),
    ('トップス', 'トップス'),
    ('ボトムス', 'ボトムス'),
    ('靴', '靴'),
    ('ストール', 'ストール'),

)


def get_or_create_parts():
    parts = Parts.objects.get_or_create()
    return parts


class Parts(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now)
    cloth_name = models.CharField(verbose_name='ブランド名', max_length=50)
    date_purchase = models.DateField(verbose_name='購入日', null=True, blank=True)
    season = models.CharField(verbose_name='季節', max_length=5, choices=SEASONS_CHOICES)
    part = models.ForeignKey(Parts, verbose_name="部位",
                             on_delete=models.CASCADE)
    image = models.ImageField(verbose_name='写真', upload_to='photos/', null=True, blank=True,
                              height_field=None, width_field=None, max_length=None)
    price = models.IntegerField(verbose_name='価格', validators=[
                                validators.MinValueValidator(0)], null=True, blank=True)
    favorite = models.BooleanField(("お気に入り"), null=True, blank=True, default=False)

    # user = models.ForeignKey(CustomUser, verbose_name='ユーザ', on_delete=models.CASCADE)

    def __str__(self):
        return self.cloth_name

show/forms.py
from django import forms
from .models import Post, Parts
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('cloth_name', 'date_purchase', 'season',
                  'part', 'price',  'image')
        widgets = {
            'date_purchase': forms.SelectDateWidget
        }


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class PartsForm(forms.ModelForm):
    class Meta():
        model = Parts
        fields = ('name',)


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

show/views.py
from django.views.generic import ListView, CreateView, DeleteView
from .models import Post, Parts
from .forms import PostForm, LoginForm, PartsForm, SignUpForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, LogoutView)
from django.contrib.auth import login
from django.http import HttpResponseRedirect

# Create your views here.


SEASONS_CHOICES = (
    '春',
    '夏',
    '秋',
    '冬',
)


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = "show/index.html"
    context_object_name = 'posts'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)

        parts = Parts.objects.all()
        seasons = SEASONS_CHOICES
        context['parts'] = parts
        context['seasons'] = seasons
        return context

    def get_queryset(self):
        results = self.model.objects.all()
        results = results.filter(user=self.request.user).order_by('-date_created')

        q_parts = self.request.GET.getlist('part')
        q_seasons = self.request.GET.getlist('season')
        if len(q_parts) != 0:

            parts = [x for x in q_parts if x in ["1", "2", "3", "4", "5"]]
            results = results.filter(part__in=parts)
        if len(q_seasons) != 0:
            seasons = [x for x in q_seasons if x in ["春", "夏", "秋", "冬"]]
            results = results.filter(season__in=seasons)
        return results


class PostCreateView(CreateView):
    model = Post
    template_name = "form"
    template_name = "show/post_create.html"
    success_url = "/"
    form_class = PostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PartsCreateView(CreateView):
    model = Parts
    template_name = "show/parts_create.html"
    success_url = "/parts_create"
    form_class = PartsForm


class PostDelete(DeleteView):
    model = Post
    context_object_name = 'delete_post'
    success_url = reverse_lazy('show:home')
    template_name = "show/post_confirm_delete.html"


class Login(LoginView):
    form_class = LoginForm
    template_name = "user/login.html"


class Logout(LoginRequiredMixin, LogoutView):
    template_name = "user/login.html"


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = "show/signup.html"
    success_url = reverse_lazy('show:home')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())

user/views.py
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import SignUpForm

# Create your views here.


class UserCreateView(CreateView):
    form_class = SignUpForm
    template_name = 'user/create.html'
    success_url = reverse_lazy('show:home')

    '''def form_valid(self, form):
        print(self.request.POST['next'])
        if self.request.POST['next'] == 'back':
            return render(self.request, 'user/create.html', {'form': form})
        elif self.request.POST['next'] == 'confirm':
            return render(self.request, 'user/create_confirm.html', {'form': form})
        elif self.request.POST['next'] == 'user':
            form.save()
            # 認証
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )
            # ログイン
            login(self.request, user)
            return super().form_valid(form)
        else:
            # 通常このルートは通らない
            return redirect(reverse_lazy('show:home'))
    '''

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())  # リダイレクト

templates/show/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<title>Show</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/application.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" role="navigation">
    <a class="navbar-brand" href="{% url 'show:home' %}">Cloth Show</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'show:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'show:post_create' %}" target="_self">New</a>
            </li>
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'show:parts_create' %}" target="_self">Add Parts</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="">User Name : {{user.get_username}}</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'show:login' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'show:logout' %}">Login</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="">ユーザー登録</a>
            </li>
            {% endif %}

            <!--<li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown1</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a>Action 1</a></li>
                    <li class="dropdown-item dropdown">
                        <a class="dropdown-toggle" id="dropdown1-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown1.1</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown1-1">
                            <li class="dropdown-item" href="#"><a>Action 1.1</a></li>
                            <li class="dropdown-item dropdown">
                                <a class="dropdown-toggle" id="dropdown1-1-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown1.1.1</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown1-1-1">
                                    <li class="dropdown-item" href="#"><a>Action 1.1.1</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown2</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown2">
                    <li class="dropdown-item" href="#"><a>Action 2 A</a></li>
                    <li class="dropdown-item" href="#"><a>Action 2 B</a></li>
                    <li class="dropdown-item" href="#"><a>Action 2 C</a></li>
                    <li class="dropdown-item dropdown">
                        <a class="dropdown-toggle" id="dropdown2-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown2.1</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown2-1">
                            <li class="dropdown-item" href="#"><a>Action 2.1 A</a></li>
                            <li class="dropdown-item" href="#"><a>Action 2.1 B</a></li>
                            <li class="dropdown-item" href="#"><a>Action 2.1 C</a></li>
                            <li class="dropdown-item dropdown">
                                <a class="dropdown-toggle" id="dropdown2-1-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown2.1.1</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown2-1-1">
                                    <li class="dropdown-item" href="#"><a>Action 2.1.1 A</a></li>
                                    <li class="dropdown-item" href="#"><a>Action 2.1.1 B</a></li>
                                    <li class="dropdown-item" href="#"><a>Action 2.1.1 C</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-item dropdown">
                                <a class="dropdown-toggle" id="dropdown2-1-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown2.1.2</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown2-1-2">
                                    <li class="dropdown-item" href="#"><a>Action 2.1.2 A</a></li>
                                    <li class="dropdown-item" href="#"><a>Action 2.1.2 B</a></li>
                                    <li class="dropdown-item" href="#"><a>Action 2.1.2 C</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
    </div>
</nav>
    {% block content %}
    {% endblock content %}
    <script　type="text/javascript" src="{% static 'js/application.js' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</body>

</html>

templates/show/index.html
{% extends 'show/base.html' %}
{% load static %}
{% load custom_filters %}
{% load custom_tags %}
{% block content %}
<div class="container py-5">
    <div class="row text-center text-white mb-5">
        <div class="col-lg-7 mx-auto">
            <h1 class="display-4">Purchased List</h1>
        </div>
    </div>

<form method="get" action="" name="filter_form">
    <legend>絞り込み条件</legend>
    <div>
        <span>部位：</span>
        {% for part in parts %}
            <input type="checkbox" id="filter_kind_{{ part.pk }}" 
                name="part" 
                value="{{ part.pk }}"
                {{ part.pk|checked:request.GET }}
                >{{ part.name }}
        {% endfor %}
    </div>

    <div>
        <span>季節：</span>
        {% for i in seasons %}
            <input type="checkbox" id="filter_season" 
                name="season" 
                value="{{ i }}"
                {{ i |season_checked:request.GET}}
                >{{i}}
        {% endfor %}
    </div>

    <div>
        <button id="filter">絞り込み</button>
    </div>
</form>

<div>
    {% if posts %}
        合計：{{posts.count}}
    {% endif %}
</div>
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <!-- List group-->
            {% for list in object_list %}
            <ul class="list-group shadow">
                <!-- list group item-->
                <li class="list-group-item">
                    <!-- Custom content-->
                      <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                        <div class="media-body order-2 order-lg-1">
                            
                            <p>ブランド名：{{list.cloth_name}}</p>
                            {% if list.date_purchase %}
                              <p>購入日：{{list.date_purchase}}</p>
                            {% endif %}
                            {% if list.season %}
                              <p>季節：{{list.season}}</p>
                            {% endif %}
                            <p>部位：{{list.part.name}}</p>
                            <p>値段：{{list.price}}円</p>
                            <img src="{{MEDIA_URL}}{{list.image}}" style="width:300px;height:auto">
                            <p><a href="{% url 'show:delete' list.pk %}">削除</a></p>
                            
                        </div> <!-- End -->
                      </div>
                </li> <!-- End -->
                <!-- list group item-->
            </ul>
            {% endfor %}
        </div>
    </div>

{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="{% url 'show:home' %}?{% query_string request page_obj.previous_page_number %}">previous</a></li>
        {% endif %}
        {% for link_page in page_obj.paginator.page_range %}
            {% if link_page == page_obj.number %}
                <li class="active">{{ link_page }}</li>
            {% else %}
                <li><a href="{% url 'show:home' %}?{% query_string request link_page %}">{{ link_page }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li><a href="{% url 'show:home' %}?{% query_string request page_obj.next_page_number %}">next</a></li>
        {% endif %}
    </ul>
{% endif %}

<button type="button" name="new_post" onclick="location.href='{% url 'show:post_create' %}'">新規作成</button>
{% endblock content %}

<!--


<table align="center" border="1">
  {% for list in posts %}
  <div class="containe">
    <tr>
      <td>{{list.cloth_name}}</td>
      <td>
        {% if list.datate_purchase %}
        {{list.date_purchase}}
        {% endif %}
      </td>
      <td>
        {% if list.season %}
        {{list.season}}
        {% endif %}
      </td>
      <td>
        {{list.part}}
      </td>

      <td>
        <img src="{{MEDIA_URL}}{{list.image}}" style="width:300px;height:auto">
      </td>
    </tr>

  </div>
  {% endfor %}
</table>
<button type="button" name="new_post" onclick="location.href='{% url 'show:post_create' %}'">新規作成</button>

-->

templates/show/parts_create.html
{% extends 'show/base.html' %}
{% load static %}
{% block content %}

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <button type="submit">save</button>
    </form>
{% endblock content %}

templates/show/post_confirm_delete.html
{% extends 'show/base.html' %}
{% load static %}
{% block content %}
    <h1>削除確認</h1>
    <form method="post">
        {% csrf_token %}
        <p>{{ delete_post.cloth_name }}/{{ delete_post.date_purchase }}/{{ delete_post.season }}/{{delete_post.part}}</p>
        <p><img src="{{MEDIA_URL}}{{delete_post.image}}" style="width:300px;height:auto"></p>
        <p>を削除しますか？</p>
        <input type="submit" value="削除する">
    </form>
{% endblock content %}

templates/show/post_create.html
{% extends 'show/base.html' %}
{% load static %}
{% block content %}

    <form method="post" enctype="multipart/form-data"　id="post_create">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>  
    <button type="submit">save</button>
    </form>
{% endblock content %}

templates/show/signup.html
<!DOCTYPE html>
<html lang="ja">
<head>
</head>

<body>
    <main>
    {# signup処理部分 #}
    <form method="post" action="{% url 'show:signup' %}">
    {% csrf_token %}
    <table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.email.label_tag }}</td>
        <td>{{ form.email }}</td>
    </tr>
    <tr>
        <td>{{ form.password1.label_tag }}</td>
        <td>{{ form.password1 }}</td>
    </tr>
    <tr>
        <td>{{ form.password2.label_tag }}</td>
        <td>{{ form.password2 }}</td>
    </tr>
    </table>

    <input type="submit" value="login" />

    {# エラーメッセージを表示 #}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p>{{ error }}</p>
            {% endfor %}
        {% endfor %}
    {% endif %} 
    </form>

</body>

templates/user/create.html
{% extends 'show/base.html' %}
{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>ユーザー作成</h3></div>
                <form class="ui form" action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="ui orange button" name="next" value="confirm" type="submit">確認</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/user/create_confirm.html
{% extends 'show/base.html' %}
{% block title %}Show{{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <i class="right angle icon divider"></i>
            <a class="active section">ユーザー作成</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>ユーザー作成</h3></div>
                <table  class="ui celled table table table-hover" >
                    <tr><td>お名前</td><td>{{form.cleaned_data.username}}</td></tr>
                    <tr><td>パスワード</td><td>********</td></tr>
                </table>
                <form class="ui form" action="" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    {{field.as_hidden}}
                    {% endfor %}
                    <button class="ui button" name="next" value="back" type="submit">修正</button>
                    <button class="ui orange button" name="next" value="regist" type="submit">登録</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Login</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.12/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.12/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.12/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.12/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.12/plugins/iCheck/square/blue.css' %}">

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <b>Login</b>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg"></p>

      <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group has-feedback">
            {{ field }}
          </div>
        {% endfor %}
        <div class="row">

          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              <p>{{ error }}</p>
            </div>
          {% endfor %}
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">ログオン</button>
          </div>
          <div class="col-xs-4">
            <button type="button" name="create_user" onclick="location.href='{% url 'show:signup' %}'">新規登録</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

  <!-- jQuery 3 -->
  <script src="{% static 'AdminLTE-2.4.12/bower_components/jquery/dist/jquery.min.js' %}"></script>
  <!-- Bootstrap 3.3.7 -->
  <script src="{% static 'AdminLTE-2.4.12/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <!-- iCheck -->
  <script src="{% static 'AdminLTE-2.4.12/plugins/iCheck/icheck.min.js' %}"></script>
</body>
</html>